#!/bin/bash
SERVICE_PORT=${SERVICE_PORT:-"1701"}
KEY_SIZE=${KEY_SIZE:-"1024"}
USER_ID=${USER_ID:-"ziozzang"}
E_MAIL=${E_MAIL:-"ziozzang@gmail.com"}
USER_PW=${USER_PW:-"loginme"}


[[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)
LOCAL_IP=`ifconfig eth0 | grep -m 1 'inet addr:' | cut -d: -f2 | awk '{print $1}'`
DEFAULT_GW=`route -n | grep "^0.0.0.0"  | awk '{print $2}'`

IPF=`cat /etc/sysctl.conf  | grep "^net.ipv4.ip_forward" | wc -l`
if [[ "$IPF" -eq "0" ]]; then
  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
echo 1 > /proc/sys/net/ipv4/ip_forward

apt-get update -fy
cat <<EOF | debconf-set-selections
openswan openswan/install_x509_certificate select true
openswan openswan/how_to_get_x509_certificate select create
openswan openswan/restart select true
openswan openswan/runlevel_changes note
openswan openswan/x509_self_signed select true
openswan openswan/x509_country_code select KR
EOF

DEBIAN_FRONTEND=noninteractive apt-get install --yes --force-yes  openswan

#cp /etc/ipsec.d/examples/l2tp-psk.conf /etc/ipsec.d/l2tp-psk.conf
#sed -i -e "s,\(left\)=YourGatewayIP,\1=${LOCAL_IP},g" /etc/ipsec.conf
#sed -i -e "s,\(leftnexthop\)=YourGatewayIP,\1=${DEFAULT_GW},g" /etc/ipsec.conf
#echo "include /etc/ipsec.d/l2tp-psk.conf" >> /etc/ipsec.conf
cat > /etc/ipsec.conf << EOF
config setup
    nat_traversal=yes
    protostack=netkey
    #plutostderrlog=/tmp/log.txt (for debugging)

conn L2TP-PSK
    authby=secret
    pfs=no
    rekey=no
    type=tunnel
    esp=aes128-sha1
    ike=aes128-sha-modp1024
    ikelifetime=8h
    keylife=1h
    left=${LOCAL_IP}
    leftnexthop=%defaultroute
    leftprotoport=17/1701
    right=%any
    rightprotoport=17/%any
    rightsubnetwithin=0.0.0.0/0
    auto=add
    dpddelay=30
    dpdtimeout=120
    dpdaction=clear

EOF
service ipsec restart
update-rc.d ipsec defaults

#====

apt-get install -fy xl2tpd ppp



cat > /etc/ipsec.secrets << EOF
%any %any: PSK "${USER_PW}"
EOF

mv /etc/xl2tpd/xl2tpd.conf /etc/xl2tpd/xl2tpd.conf.sample
cat > /etc/xl2tpd/xl2tpd.conf << EOF
[global]

[lns default]    
ip range = 10.245.0.2-10.245.0.200
local ip = ${LOCAL_IP}
length bit = yes
require chap = yes
refuse pap = yes
require authentication = yes
pppoptfile = /etc/ppp/options.xl2tpd
EOF

cat > /etc/ppp/options.xl2tpd << EOF
ipcp-accept-local
ipcp-accept-remote
ms-dns 8.8.8.8
noccp
auth
crtscts
idle 1800
mtu 1410
mru 1410
nodefaultroute 
lock
proxyarp
connect-delay 5000
EOF

cat >> /etc/ppp/chap-secrets << EOF
${USER_ID} l2tpd ${USER_PW} *
EOF

IPF=`iptables-save  | grep "10.245.0.0" | wc -l`
if [[ "$IPF" -eq "0" ]]; then
  iptables -A FORWARD -s 10.245.0.0/24 -j ACCEPT
  iptables -t nat -A POSTROUTING -s 10.245.0.0/24 -o eth0 -j MASQUERADE
fi
wget -qO- https://raw.github.com/ziozzang/home-server/master/vpn/install-preserve-iptables-ubuntu | bash

ufw allow 500/udp
ufw allow 4500/udp
ufw allow 1701/udp

service xl2tpd restart
update-rc.d xl2tpd defaults

