#!/bin/bash
if [ ! -f "/etc/iptables.rules" ]; then
  iptables-save > /etc/iptables.rules
fi

cat > /etc/network/if-pre-up.d/iptables << EOF
#!/bin/sh
iptables-restore < /etc/iptables.rules
exit 0
EOF

cat > /etc/network/if-post-down.d/iptables << EOF
#!/bin/sh
iptables-save -c > /etc/iptables.rules
if [ -f /etc/iptables.rules ]; then
 iptables-restore < /etc/iptables.rules
fi
exit 0
EOF

sudo chmod +x /etc/network/if-post-down.d/iptables
sudo chmod +x /etc/network/if-pre-up.d/iptables
