#!/bin/bash

# wget -qO- https://raw.github.com/ziozzang/home-server/master/install-new-user | bash
USER_ID=${USER_ID:-"ziozzang"}
KEY_URL=${KEY_URL:-"http://home.jioh.net/pxe/authorized_keys"}

[[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)


sed -i -e "s,^\(exit\),#\1,g" /etc/rc.local
cat >> /etc/rc.local << EOF
cat /etc/rc.run_once 2> /dev/null | /bin/bash  >> /var/log/rc.run_once.log 2>1 &
EOF

cat > /etc/rc.run_once << EOF
#!/bin/bash
mkdir -p /root/.ssh
cd /root/.ssh
rm -f /root/.ssh/authorized_keys
wget -O authorized_keys ${KEY_URL}
cat > /root/.ssh/config << EFF
Host *
    StrictHostKeyChecking no
EFF
chmod -R 700 /root/.ssh
touch /root/.ssh/known_hosts
chmod 600 /root/.ssh/known_hosts

cp -rf /root/.ssh /home/${USER_ID}
chown -R ${USER_ID}:${USER_ID} /home/${USER_ID}/.ssh
chmod -R 700 /home/${USER_ID}/.ssh
touch /home/${USER_ID}/.ssh/known_hosts
chmod 600 /home/${USER_ID}/.ssh/known_hosts

locale-gen ko_KR.UTF-8
wget -qO- https://raw.github.com/ziozzang/home-server/master/install-ntpsync | bash

cnt=`ufw status | grep 22 | wc -l`
if [[ "${cnt}" -eq "0" ]]; then
  ufw allow 22
fi

cat > /etc/sudoers.d/${USER_ID} << EFF
${USER_ID} ALL=(ALL) NOPASSWD: ALL
EFF
chmod 440 /etc/sudoers.d/${USER_ID}

# Delete SELF
rm -f /etc/rc.run_once
EOF
