#!/bin/bash
# Install necessary files
apt-get install -fy git-core build-essential
apt-get install -fy libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make

# Clone Repo
git clone --recursive https://github.com/vysheng/tg.git

# Build
cd tg
./configure
make

# Install
mkdir -p /etc/telegram-cli/
cp tg-server.pub /etc/telegram-cli/server.pub
cp bin/telegram-cli /usr/bin/


exit 0
wget https://bugs.launchpad.net/~miry/+archive/ppa/+files/telegram-cli_0.0.20140125-1_amd64.deb
sudo dpkg -i ./telegram-cli_0.0.20140125-1_amd64.deb
sudo apt-get -f install

telegram -k /etc/telegram/tg.pub
