#!/bin/bash
SERVICE_PORT=${SERVICE_PORT:-"1723"}
KEY_SIZE=${KEY_SIZE:-"1024"}
USER_ID=${USER_ID:-"ziozzang"}
E_MAIL=${E_MAIL:-"ziozzang@gmail.com"}
USER_PW=${USER_PW:-"loginme"}

apt-get update -fy
apt-get install -fy pptpd

cat >> /etc/pptpd.conf << EOF
localip 10.244.0.1
remoteip 10.244.0.100-200
EOF

cat >> /etc/ppp/chap-secrets << EOF
${USER_ID} pptp ${USER_PW} *
EOF

cat >> /etc/ppp/pptpd-options << EOF
ms-dns 8.8.8.8
ms-dns 8.8.4.4
EOF

service pptpd restart

IPF=`cat /etc/sysctl.conf  | grep "^net.ipv4.ip_forward" | wc -l`
if [[ "$IPF" -eq "0" ]]; then
  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && iptables-save
iptables --table nat --append POSTROUTING --out-interface ppp0 -j MASQUERADE
iptables -I INPUT -s 10.244.0.0/8 -i ppp0 -j ACCEPT
iptables --append FORWARD --in-interface eth0 -j ACCEPT

ufw allow ${SERVICE_PORT}/tcp
service pptpd start
update-rc.d pptpd defaults
