#!/bin/bash
SERVICE_PORT=${SERVICE_PORT:-"1723"}
KEY_SIZE=${KEY_SIZE:-"1024"}
USER_ID=${USER_ID:-"ziozzang"}
E_MAIL=${E_MAIL:-"ziozzang@gmail.com"}
USER_PW=${USER_PW:-"loginme"}


[[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)
LOCAL_IP=`ifconfig eth0 | grep -m 1 'inet addr:' | cut -d: -f2 | awk '{print $1}'`
DEFAULT_GW=`route -n | grep "^0.0.0.0"  | awk '{print $2}'`

IPF=`cat /etc/sysctl.conf  | grep "^net.ipv4.ip_forward" | wc -l`
if [[ "$IPF" -eq "0" ]]; then
  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
echo 1 > /proc/sys/net/ipv4/ip_forward

apt-get update -fy
apt-get install -fy openswan
cat <<EOF | debconf-set-selections
openswan openswan/install_x509_certificate true
openswan openswan/how_to_get_x509_certificate create
EOF


cp /etc/ipsec.d/examples/l2tp-psk.conf /etc/ipsec.d/l2tp-psk.conf
sed -i -e "s,\(left\)=YourGatewayIP,\1=${LOCAL_IP},g" /etc/openvpn/easy-rsa/vars
sed -i -e "s,\(leftnexthop\)=YourGatewayIP,\1=${DEFAULT_GW},g" /etc/openvpn/easy-rsa/vars
echo "include /etc/ipsec.d/l2tp-psk.conf" >> /etc/ipsec.conf

service ipsec restart
update-rc.d ipsec defaults

#====

apt-get install -fy xl2tpd ppp
mv /etc/xl2tpd/xl2tpd.conf /etc/xl2tpd/xl2tpd.conf.sample
cat > /etc/xl2tpd/xl2tpd.conf << EOF
[global]   
port = ${SERVICE_PORT}

[lns default]    
ip range = 10.7.0.2-10.7.0.20
local ip = 10.7.0.1
length bit = yes
require chap = yes
refuse pap = yes
require authentication = yes
pppoptfile = /etc/ppp/options.xl2tpd
EOF

cat > /etc/ppp/options.xl2tpd << EOF
require-mschap-v2
ms-dns 168.126.63.1
asyncmap 0
auth
crtscts
lock
hide-password
modem
debug
name l2tpd
proxyarp
lcp-echo-interval 30
lcp-echo-failure 4
EOF

cat >> /etc/ppp/chap-secrets << EOF
${USER_ID} l2tpd ${USER_PW} *
EOF


iptables -A FORWARD -s 10.7.0.0/24 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.7.0.0/24 -o eth0 -j MASQUERADE

ufw allow ${SERVICE_PORT}/tcp

service xl2tpd restart
update-rc.d xl2tpd defaults

